M48
; DRILL file KiCad 10.0.5 date 2026-07-30T21:51:39
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-30T21:51:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.000
%
G90
G05
T1
X126.75Y-102.775
T2
X146.75Y-102.775
T3
X136.75Y-58.0
X136.75Y-70.0
T4
X129.5Y-53.5
X129.5Y-111.5
X152.5Y-53.5
X152.5Y-111.5
M30
